version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./craft-virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf

    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: craft

    volumes:
      - ./db:/var/lib/mysql
